- hosts: terraform-ansible
  tasks:
  - name: Instlaando o python3 e o virtualenv
    apt:
      pkg: 
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencias com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/estudo/venv
      name:
        - django
        - djangorestframework
  - name: Iniciando projeto 
    shell: '. /home/ubuntu/estudo/venv/bin/activate; django-admin startproject setup /home/ubuntu/estudo'
    ignore_errors: yes
  - name: Alterando o hosts do settings
    lineinfile:
      path: /home/ubuntu/estudo/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes